#! /usr/bin/env bash

## opts parsing, see https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -n|--nrepl)
            USE_NREPL=YES
            shift # past argument
            ;;
    esac
done

echo foo

set -- "${POSITIONAL[@]}" # restore positional parameters

echo bar

## end opts parsing

if [[ -n ${USE_NREPL} ]]; then
    echo "Starting vaulisp REPL (with NREPL server)"
    clj \
        -A:nrepl \
        -m nrepl.cmdline \
        --middleware "[cider.nrepl/cider-middleware]" \
        --interactive
else
    echo "Starting vaulisp REPL"
    clj -M -m egg.vaulisp
fi
